### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by lvian** [raphaelluchini/popcorntime-smarttv-server#4]
Hello guys,

Can we get a bit more documentation on this application?

After downloading, I run it I get the expected "Server running on ..." message.

But then when I run the smarttv app I just get a black screen.

There are any folder requirementes? Should I put the server with something else? Maybe change some configuration? Any infomartion would help.

Thanks

**Comment by dikani** [comment]
did u get this running somehow? got exact the same problem..
